version: '3.10'
services:
  redis:
    image: redis:latest
    command:
     - redis-server
    env_file:
        - ./.env
    restart: on-failure

    ports:
      - "6379:6379"
  db:
    image: postgres:14-latest
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    build: ..
    command: sh -c "make migrate && python -m bot"
    env_file:
      -  ./.env
    restart: always


volumes:
  pgdata:

